var subnat_name_mapping = { 'GIN': {
									  0: "Boffa",
									  1: "Boke",
									  2: "Fria",
									  3: "Gaoual",
									  4: "Koundara",
									  5: "Conakry",
									  6: "Dabola",
									  7: "Dinguiraye",
									  8: "Faranah",
									  9: "Kisidougou",
									  10: "Kankan",
									  11: "Kerouane",
									  12: "Kouroussa",
									  13: "Mandiana",
									  14: "Siguiri",
									  15: "Coyah",
									  16: "Dubreka",
									  17: "Forecariah",
									  18: "Kindia",
									  19: "Telimele",
									  20: "Koubia",
									  21: "Labe",
									  22: "Lelouma",
									  23: "Mali",
									  24: "Tougue",
									  25: "Dalaba",
									  26: "Mamou",
									  27: "Pita",
									  28: "Beyla",
									  29: "Gueckedou",
									  30: "Lola",
									  31: "Macenta",
									  32: "NZerekore",
									  33: "Yomou"
									},
							'LBR': {
									  0: "Nimba",
									  1: "Rivercess",
									  2: "River Gee",
									  3: "Sinoe",
									  4: "Bomi",
									  5: "Bong",
									  6: "Gbarpolu",
									  7: "Grand Cape Mount",
									  8: "Grand Bassa",
									  9: "Grand Gedeh",
									  10: "Grand Kru",
									  11: "Lofa",
									  12: "Margibi",
									  13: "Maryland",
									  14: "Montserrado"
									},

							'SLE': {
									  0: "Kailahun",
									  1: "Kenema",
									  2: "Kono",
									  3: "Bombali",
									  4: "Kambia",
									  5: "Koinadugu",
									  6: "Port Loko",
									  7: "Tonkolili",
									  8: "Bo",
									  9: "Bonthe",
									  10: "Moyamba",
									  11: "Pujehun",
									  12: "Western (rural)",
									  13: "Western (urban)"
									}



					}